name: Validate Source Code

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - homolog

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20 
      - name: Install Dependencies
        run: npm install
      - name: Run Lint
        run: npm run lint
      - name: Build Project
        run: CI=false npm run build
